### ISSUE TITLE
Err result image about Info-GAN in your README

### ISSUE THREAD

**Issue by primetang** [burness/tensorflow-101#2]
Hi,

[Info-GAN](https://github.com/burness/tensorflow-101/tree/master/GAN/Info-GAN) is  an unsupervised learning, `z_cat` in your code can control the `Digit type`, but the generate digit label will not be as same as your `a` in [generate.py](https://github.com/burness/tensorflow-101/blob/master/GAN/Info-GAN/generate.py), it just looks like a cluster. The true result should be like this:

`a`

4 3 4 8 1 1 3 6 1 4
9 8 0 9 3 6 9 6 1 4
6 9 0 1 0 3 3 5 7 7
7 1 1 4 0 6 2 5 0 9
0 9 3 7 2 6 8 9 9 3
7 8 2 4 7 5 6 8 1 4
9 5 8 2 2 5 0 9 6 1
2 3 2 0 0 5 7 7 1 8
1 9 8 4 6 2 1 4 5 4
3 6 1 2 3 1 7 0 3 0

`fake.png'
![fake](https://cloud.githubusercontent.com/assets/7023014/22811500/23d44368-ef7a-11e6-813b-9275bc8503a5.png)

`sample.png`
![sample](https://cloud.githubusercontent.com/assets/7023014/22811512/33b40b92-ef7a-11e6-8b4b-826327c7e2ca.png)

In fact, when `z_cat` is `1, 0, 0, 0, 0, 0, 0, 0, 0, 0`, the generate digit is `4` but not `0` in the above result. It's a random correspondence. I think you have attacted the result image from `AC-GAN` but not `Info-GAN`, please check it again.

**Comment by burness** [comment]
Yes you are right, Info-Gan just generate the disentangled representation but no labels info, i was also doubt it, but it seems the result image is from Info-Gan, anywhere I will check it again. Thanks for running this project

**Comment by burness** [comment]
@primetang  Yes, I rerun the result you are right, Maybe I just scp the wrong folder 😆   Thanks!!!

**Comment by primetang** [comment]
You are welcome! And I will close this discussion.
