### ISSUE TITLE
zhihu_code no data provided

### ISSUE THREAD

**Issue by brisker** [burness/tensorflow-101#5]
https://github.com/burness/tensorflow-101/tree/master/zhihu_code/src
Where to get the training and test dataset?

**Comment by burness** [comment]
you can change the num in [](https://github.com/burness/tensorflow-101/blob/master/zhihu_code/src/gen_verification.py#L75) to generate the train dataset and test dataset.

**Comment by brisker** [comment]
@burness 
Sorry, I am new to this, but where is the "num" parameter? In gen_verification.py?

**Comment by brisker** [comment]
@burness 
But where are the images stored? I can only find "sample" folder. If I change 
for i in range(10):
to 
for i in range(10000):
then where are the 10000 images stored? I can not find them.

**Comment by burness** [comment]
@brisker  It's saved in the folder of your gen_verification.p, here the reason you can't get the images is the exception maybe you have not change the `fontPath = '/Library/Fonts/Arial Unicode.ttf',`  make sure that you have a ttf in your path
