### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by sinsa110** [burness/tensorflow-101#7]
最近在学习TF，研究大牛的代码报类型错误，具体报错位置见https://github.com/burness/tensorflow-101/blob/master/zhihu_code/src/train.py 的118行和119行，

我是刚学习的菜鸟，不知道是不是版本问题（我尝试了1.0.0和0.0.2两个版本，都报错了）。

解决办法：
`out_score = tf.concat(values=[out0, out1, out2, out3, out4, out5, out6, out7, out8, out9], concat_dim=1, name="concat") ## axis=1 改为 concat_dim=1
    out_final = tf.cast(tf.concat(values=[out0_argmax, out1_argmax, out2_argmax, out3_argmax, out4_argmax, out5_argmax, out6_argmax, out7_argmax, out8_argmax, out9_argmax], concat_dim=1), tf.int32)
`

**Comment by burness** [comment]
@sinsa110 我看 api [concat tensorflow 1.0](https://www.tensorflow.org/api_docs/python/tf/concat) 是我那样用的，另外我在tensorflow 1.0.0上也可以跑起来，
![image](https://cloud.githubusercontent.com/assets/3112825/23410058/d7b7037e-fe08-11e6-80ab-8ab33d98555d.png)

奇怪了（不要太care计算时间，因为我是在云上用的外挂的硬盘） 你能打印下 `python -c 'import tensorflow as tf; print tf.__version__'`来看看吗
![image](https://cloud.githubusercontent.com/assets/3112825/23409494/be11a426-fe06-11e6-9030-58ae9adf3e45.png)

**Comment by suntao2012** [comment]
because of API changed in TF new version-1.0. you can change tf.concat(value, axis) to tf.concat(axis, value) without the key arg if you used old tf version

**Comment by burness** [comment]
@suntao2012  Maybe run the 'tf_upgrade.py' is a better way to solve the problem

**Comment by sinsa110** [comment]
python -c 'import tensorflow as tf; print tf.__version__' 的结果如下：
![image](https://cloud.githubusercontent.com/assets/13688310/23941876/6d53bf10-09a5-11e7-8205-630303efa798.png)

**Comment by sinsa110** [comment]
@burness python -c 'import tensorflow as tf; print tf.version' 的结果如下：
![](https://cloud.githubusercontent.com/assets/13688310/23941876/6d53bf10-09a5-11e7-8205-630303efa798.png)

**Comment by sinsa110** [comment]
@suntao2012 你的方法解决问题了。
